name: CI Pipeline with Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # SonarQube için tam git history

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Generate Test Coverage Report
        run: mvn jacoco:report

      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=ci-cd-demo \
          -Dsonar.projectName='ci-cd-demo' \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo "Waiting for SonarQube to process results..."
          sleep 10
          
          RESULT=$(curl -s -u ${SONAR_TOKEN}: "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=ci-cd-demo")
          STATUS=$(echo $RESULT | jq -r '.projectStatus.status')
          
          echo "Quality Gate Status: $STATUS"
          
          if [ "$STATUS" != "OK" ]; then
            echo "❌ Quality Gate failed!"
            echo "Details: $RESULT"
            exit 1
          else
            echo "✅ Quality Gate passed!"
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: target/site/jacoco