name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ci-cd-demo:latest .

      - name: Test Docker image
        run: |
          docker run -d -p 8080:8080 ci-cd-demo:latest
          sleep 15
          curl http://localhost:8080/status || exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker tag ci-cd-demo:latest ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest